apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    backend: python
spec:
  containers:
  - image: srcmeshcourse/nginx-log-path:0.1
    name: nginx
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /var/log/nginx/
      name: log-volume
  - image: srcmeshcourse/fluentd-tail:0.1
    name: fluentd
    volumeMounts:
    - mountPath: /var/log/
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}